# -*- coding: utf-8 -*-
"""Profit_MKT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13gsGElUEp_9qw8elbnyjVcB9iDOna4ls
"""

#import thư viện
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt #Thư viện cho vẽ hình
plt.rcParams.update({'figure.figsize':(7,3), 'figure.dpi':120})

link='https://drive.google.com/file/d/1JmOgZGM-4MYumG1ALz5W56Edur69MAeN/view?usp=sharing'

path = 'https://drive.google.com/uc?export=download&id='+link.split('/')[-2]
df = pd.read_csv(path)

df.head()
#df.info()
#df.describe()

plt.xlabel('Marketing (200$)',fontsize=12)
plt.ylabel('Lợi nhuận (200$)',fontsize=12)
plt.grid()
plt.scatter(df.Marketing, df.Profit, color='red', marker='o')

from sklearn import linear_model
from sklearn.linear_model import LinearRegression

model_lin=linear_model.LinearRegression()

X=df[['Marketing']]
y=df.Profit

model_lin.fit(X,y)

print('a=',model_lin.coef_)
print('b=',model_lin.intercept_)

print('Phương trình hồi quy tuyến tính cần tìm là: y = 0.2x + 70')

#Dự báo
y_pred=model_lin.predict(df[['Marketing']])

c=model_lin.predict([[500]])
print(c)

y_pred

plt.xlabel('Chi phí Marketing (500$)',fontsize=13)
plt.ylabel('Lợi nhuận (200$)',fontsize=13)
plt.scatter(df.Marketing, df.Profit, color='blue', marker='o')
plt.plot(df.Marketing,y_pred, color='red', label = 'y dự báo')
plt.legend()
plt.grid()

#4. Tính toán độ chính xác
from sklearn.metrics import r2_score
Ac=r2_score(df.Profit, y_pred)
print('The accuracy of this model is:R-square=',"{:.2f}".format(Ac))